// src/lib/data.ts — Base seed & mock data for BorrowBuddy (Indian Localisation)
import type { User, Item, BorrowRequest, Activity, Category, Campus } from '../types';

export const INDIAN_CAMPUSES: Campus[] = [
  'Central Library',
  'Science Block',
  'Boys Hostel',
  'Girls Hostel',
  'Sports Complex',
  'Engineering Block',
  'Student Activity Centre',
  'Canteen Court',
];

export const MOCK_USERS: User[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@iitd.ac.in',
    trustScore: 92,
    memberSince: '2024-08-15T10:00:00Z',
    itemsBorrowed: 18,
    itemsLent: 24,
    onTimeReturns: 18,
    totalReturns: 18,
    verified: true,
    course: 'B.Tech CSE, Year 3',
    avatarColor: '#4338CA',
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@bits-pilani.ac.in',
    trustScore: 94,
    memberSince: '2024-07-20T12:00:00Z',
    itemsBorrowed: 12,
    itemsLent: 15,
    onTimeReturns: 12,
    totalReturns: 12,
    verified: true,
    course: 'B.Sc Chemistry, Year 2',
    avatarColor: '#0D9488',
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@nitk.edu.in',
    trustScore: 88,
    memberSince: '2024-09-01T09:00:00Z',
    itemsBorrowed: 20,
    itemsLent: 10,
    onTimeReturns: 19,
    totalReturns: 20,
    verified: true,
    course: 'B.Tech ECE, Year 4',
    avatarColor: '#FF6B4A',
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Priya Nair',
    email: 'priya.nair@aiims.edu',
    trustScore: 90,
    memberSince: '2024-08-25T14:00:00Z',
    itemsBorrowed: 15,
    itemsLent: 14,
    onTimeReturns: 15,
    totalReturns: 15,
    verified: true,
    course: 'MBBS 1st Year',
    avatarColor: '#E11D48',
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    name: 'Karthik Reddy',
    email: 'karthik.reddy@iiit.ac.in',
    trustScore: 85,
    memberSince: '2024-10-10T08:00:00Z',
    itemsBorrowed: 8,
    itemsLent: 9,
    onTimeReturns: 7,
    totalReturns: 8,
    verified: true,
    course: 'B.Tech CSE, Year 2',
    avatarColor: '#2563EB',
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@spa.ac.in',
    trustScore: 91,
    memberSince: '2024-09-12T11:00:00Z',
    itemsBorrowed: 14,
    itemsLent: 16,
    onTimeReturns: 14,
    totalReturns: 14,
    verified: true,
    course: 'Architecture, Year 3',
    avatarColor: '#7C3AED',
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    name: 'Mohammed Faiz',
    email: 'faiz.m@fms.edu',
    trustScore: 86,
    memberSince: '2025-01-15T16:00:00Z',
    itemsBorrowed: 6,
    itemsLent: 5,
    onTimeReturns: 6,
    totalReturns: 6,
    verified: true,
    course: 'MBA, 1st Year',
    avatarColor: '#059669',
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    name: 'Ishita Banerjee',
    email: 'ishita.b@srcc.du.ac.in',
    trustScore: 89,
    memberSince: '2024-09-05T10:30:00Z',
    itemsBorrowed: 11,
    itemsLent: 8,
    onTimeReturns: 11,
    totalReturns: 11,
    verified: true,
    course: 'B.Com Honours, Year 2',
    avatarColor: '#D97706',
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    name: 'Vikram Singh',
    email: 'vikram.singh@manipal.edu',
    trustScore: 82,
    memberSince: '2024-11-01T15:00:00Z',
    itemsBorrowed: 9,
    itemsLent: 6,
    onTimeReturns: 8,
    totalReturns: 9,
    verified: false,
    course: 'Pharmacy, Year 4',
    avatarColor: '#DC2626',
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    name: 'Divya Menon',
    email: 'divya.menon@nift.ac.in',
    trustScore: 87,
    memberSince: '2024-10-18T13:00:00Z',
    itemsBorrowed: 13,
    itemsLent: 11,
    onTimeReturns: 12,
    totalReturns: 13,
    verified: true,
    course: 'Design & Media, Year 2',
    avatarColor: '#DB2777',
  },
];

export const MOCK_ITEMS: Item[] = [
  // ── 1. Laptops and computing ──────────────────────────────────────────────
  {
    id: 'item-101',
    title: 'Dell Inspiron 15 Laptop (i5, 8GB RAM, 512GB SSD)',
    category: 'laptops',
    description: 'Clean Ubuntu 24.04 and Windows dual-boot setup. Perfect for project evaluations, viva presentations, or coding assignments.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 5000,
    deposit: 5000,
    minTrustRequired: 70,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 101,
    distance: 0.4,
    campus: 'Central Library',
    rules: ['Return with factory reset state or guest profile', 'Keep in padded laptop sleeve', 'No liquid near keyboard'],
    pickupMethod: 'Central Library ground floor discussion zone',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 14,
    createdAt: '2025-09-01T10:00:00Z',
  },
  {
    id: 'item-102',
    title: 'MacBook Air M1 (16GB RAM, 256GB SSD)',
    category: 'laptops',
    description: 'Superfast Apple Silicon laptop with battery health at 94%. Ideal for iOS app builds, video render tasks, or final year capstone demos.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 8000,
    deposit: 8000,
    minTrustRequired: 85,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 102,
    distance: 0.8,
    campus: 'Engineering Block',
    rules: ['Only for Highly Trusted borrowers (Trust 85+)', 'Strictly indoor usage in hostel or library', 'Original MagSafe cable must be returned'],
    pickupMethod: 'Engineering Block lab porch',
    maxDurationDays: 2,
    suggestedDurationDays: 2,
    rating: 5.0,
    borrowCount: 9,
    createdAt: '2025-09-03T11:30:00Z',
  },
  {
    id: 'item-103',
    title: 'Lenovo IdeaPad Slim 3 (Ryzen 5)',
    category: 'laptops',
    description: 'Lightweight 14-inch laptop configured with Python, VS Code, and MATLAB for semester lab practicals.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 4500,
    deposit: 4500,
    minTrustRequired: 70,
    available: false,
    availableFrom: '2026-10-02',
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 103,
    distance: 1.1,
    campus: 'Boys Hostel',
    rules: ['Handle with clean hands', 'Charge only with supplied 65W round-pin charger'],
    pickupMethod: 'Boys Hostel Block B entrance',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 4.8,
    borrowCount: 11,
    createdAt: '2025-09-05T09:15:00Z',
  },
  {
    id: 'item-104',
    title: 'Laptop Cooling Pad with Dual LED Fans',
    category: 'laptops',
    description: 'Ergonomic 5-angle adjustable stand with silent high-airflow USB-powered fans. Prevents thermal throttling during long coding runs.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 104,
    distance: 0.3,
    campus: 'Science Block',
    rules: ['Do not place heavy textbooks on the fan mesh', 'Return with braided USB cable'],
    pickupMethod: 'Science Block reading hall',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.7,
    borrowCount: 18,
    createdAt: '2025-09-06T14:00:00Z',
  },
  {
    id: 'item-105',
    title: 'Wireless Optical Mouse (Logitech B170)',
    category: 'laptops',
    description: 'Reliable 2.4GHz wireless mouse with nano USB receiver and fresh AA Duracell battery installed.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 105,
    distance: 0.5,
    campus: 'Girls Hostel',
    rules: ['Store nano receiver inside battery compartment when returning'],
    pickupMethod: 'Girls Hostel visitor desk',
    maxDurationDays: 7,
    suggestedDurationDays: 4,
    rating: 4.9,
    borrowCount: 27,
    createdAt: '2025-09-07T16:20:00Z',
  },
  {
    id: 'item-106',
    title: 'Mechanical Keyboard (Red Switches, Tenkeyless)',
    category: 'laptops',
    description: 'Compact TKL mechanical keyboard with quiet linear red switches and warm amber backlighting. Great for late night study sessions.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 500,
    deposit: 500,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 106,
    distance: 0.9,
    campus: 'Engineering Block',
    rules: ['No eating oily snacks while typing', 'Use keycap puller gently if cleaning'],
    pickupMethod: 'Engineering Block corridor',
    maxDurationDays: 5,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 16,
    createdAt: '2025-09-08T11:00:00Z',
  },
  {
    id: 'item-107',
    title: 'USB Hub 7-in-1 Type-C Multiport Adapter',
    category: 'adapters',
    description: 'Includes 4K HDMI, 3x USB 3.0 ports, SD/microSD card reader, and 100W Power Delivery pass-through.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 107,
    distance: 0.2,
    campus: 'Central Library',
    rules: ['Avoid yanking cable at sharp angles', 'Do not submerge or expose to spills'],
    pickupMethod: 'Central Library counter',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 31,
    createdAt: '2025-09-09T13:45:00Z',
  },
  {
    id: 'item-108',
    title: 'HDMI Cable 2m + Gold-plated VGA Adapter',
    category: 'adapters',
    description: 'High-speed braided 2-meter HDMI 2.0 cable with active HDMI-to-VGA adapter for classroom seminar projectors.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 108,
    distance: 0.6,
    campus: 'Canteen Court',
    rules: ['Coil loosely without tight kinks', 'Return plastic connector caps'],
    pickupMethod: 'Canteen Court seating pavilion',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 22,
    createdAt: '2025-09-10T15:00:00Z',
  },
  {
    id: 'item-109',
    title: 'Raspberry Pi 4 Starter Kit (4GB, Case, Heat Sinks)',
    category: 'electronics',
    description: 'Pre-flashed Raspberry Pi OS on 32GB SanDisk Extreme card, official 15W USB-C PSU, and micro-HDMI cable.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 1500,
    deposit: 1500,
    minTrustRequired: 70,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 109,
    distance: 0.7,
    campus: 'Engineering Block',
    rules: ['Do not short 40-pin GPIO headers', 'Always cleanly shutdown before unplugging power'],
    pickupMethod: 'IoT lab entrance, Engineering Block',
    maxDurationDays: 7,
    suggestedDurationDays: 4,
    rating: 5.0,
    borrowCount: 8,
    createdAt: '2025-09-11T12:00:00Z',
  },
  {
    id: 'item-110',
    title: 'Arduino Uno R3 Kit with 20+ Sensor Modules',
    category: 'electronics',
    description: 'Includes breadboard, jumper wires, ultrasonic sensor, IR module, DHT11 temp/humidity, and servo motors for robotics labs.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 800,
    deposit: 800,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 110,
    distance: 0.8,
    campus: 'Science Block',
    rules: ['Keep all resistor values in labelled plastic baggies', 'Avoid bending sensor pins'],
    pickupMethod: 'Science Block foyer',
    maxDurationDays: 7,
    suggestedDurationDays: 4,
    rating: 4.8,
    borrowCount: 14,
    createdAt: '2025-09-12T10:10:00Z',
  },
  {
    id: 'item-111',
    title: 'Pen Drive 64GB USB 3.2 + Portable HDD 1TB',
    category: 'electronics',
    description: 'Formatted in exFAT for seamless Windows and Mac file sharing. High-speed transfers for training datasets and software ISOs.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 600,
    deposit: 600,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 111,
    distance: 1.0,
    campus: 'Boys Hostel',
    rules: ['Safely eject drive before disconnecting', 'Keep inside shockproof zippered pouch'],
    pickupMethod: 'Boys Hostel Gate 2',
    maxDurationDays: 5,
    suggestedDurationDays: 2,
    rating: 4.7,
    borrowCount: 17,
    createdAt: '2025-09-13T17:00:00Z',
  },

  // ── 2. Charging, power and adapters ───────────────────────────────────────
  {
    id: 'item-201',
    title: 'Mi 20000mAh Power Bank (18W Fast Charging)',
    category: 'power-banks',
    description: 'Dual USB-A output with Type-C input/output. Charges two phones simultaneously during long semester exam days.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 800,
    deposit: 800,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 201,
    distance: 0.2,
    campus: 'Central Library',
    rules: ['Charge fully before returning', 'Do not leave in direct hot sun'],
    pickupMethod: 'Central Library 1st floor desk',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 35,
    createdAt: '2025-09-14T09:00:00Z',
  },
  {
    id: 'item-202',
    title: 'Anker PowerCore 10000mAh Ultra-Compact Power Bank',
    category: 'power-banks',
    description: 'Pocket-sized high speed PowerIQ external battery. Fits inside any blazer or backpack pencil pouch.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 500,
    deposit: 500,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 202,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Use supplied micro-USB/Type-C short cable'],
    pickupMethod: 'Girls Hostel reception',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 24,
    createdAt: '2025-09-15T11:45:00Z',
  },
  {
    id: 'item-203',
    title: 'Dell 65W Original Laptop Charger (4.5mm Barrel)',
    category: 'chargers',
    description: 'Compatible with Dell Inspiron, Vostro, and Latitude series laptops. Includes 3-pin Indian wall power cord.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 700,
    deposit: 700,
    minTrustRequired: 0,
    available: false,
    availableFrom: '2026-10-01',
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 203,
    distance: 0.7,
    campus: 'Engineering Block',
    rules: ['Do not yank cord from socket by cable', 'Indoor desk use only'],
    pickupMethod: 'Engineering Block lobby',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 19,
    createdAt: '2025-09-16T14:30:00Z',
  },
  {
    id: 'item-204',
    title: 'MacBook USB-C 67W Power Adapter + Braided Cable',
    category: 'chargers',
    description: 'Fast charges M1/M2/M3 MacBook Air and Pro laptops, as well as iPad Pro and Samsung tablets.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 800,
    deposit: 800,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 204,
    distance: 0.9,
    campus: 'Student Activity Centre',
    rules: ['Keep cable untangled in soft loop', 'Wipe clean if used in cafeteria'],
    pickupMethod: 'Student Activity Centre cafe',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 5.0,
    borrowCount: 22,
    createdAt: '2025-09-17T16:00:00Z',
  },
  {
    id: 'item-205',
    title: 'Universal All-in-One Travel Adapter (UK/US/EU/AUS)',
    category: 'adapters',
    description: 'Worldwide plug adapter with built-in dual USB ports (2.4A). Essential for foreign exchange students or imported gadgets.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 250,
    deposit: 250,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 205,
    distance: 0.3,
    campus: 'Science Block',
    rules: ['Press safety release button before sliding out pin set'],
    pickupMethod: 'Science Block main steps',
    maxDurationDays: 5,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 15,
    createdAt: '2025-09-18T10:00:00Z',
  },
  {
    id: 'item-206',
    title: 'Multi-plug Spike Guard Extension Board (4-Socket, 2m)',
    category: 'chargers',
    description: 'Heavy duty spike surge protection board with individual power switches and indicator LEDs. Room life lifesaver.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 206,
    distance: 1.2,
    campus: 'Boys Hostel',
    rules: ['Do not plug heavy immersion water heaters into this board', 'Indoor hostel use only'],
    pickupMethod: 'Boys Hostel common room',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.9,
    borrowCount: 29,
    createdAt: '2025-09-19T13:20:00Z',
  },
  {
    id: 'item-207',
    title: 'Phone Fast Charger Type-C (33W SuperVOOC/PD)',
    category: 'chargers',
    description: 'Compact 33W gallium nitride (GaN) fast wall charger with thick 1m Type-C to Type-C red power cable.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 207,
    distance: 0.5,
    campus: 'Girls Hostel',
    rules: ['Return with original red clip band'],
    pickupMethod: 'Girls Hostel visitor gate',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 26,
    createdAt: '2025-09-20T08:45:00Z',
  },
  {
    id: 'item-208',
    title: 'Micro-USB & Lightning Multi-Cable Set (Tangle-Free)',
    category: 'chargers',
    description: 'Set of two nylon-braided cables for older Kindles, Arduino boards, and iPhone devices. Tested with zero intermittent disconnects.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[9].id,
    owner: MOCK_USERS[9],
    imageSeed: 208,
    distance: 0.4,
    campus: 'Canteen Court',
    rules: ['Handle lighting pin cleanly without moisture'],
    pickupMethod: 'Canteen Court archway',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.7,
    borrowCount: 14,
    createdAt: '2025-09-21T11:00:00Z',
  },

  // ── 3. Audio and electronics ──────────────────────────────────────────────
  {
    id: 'item-301',
    title: 'Sony WH-CH520 Wireless Bluetooth Headphones',
    category: 'headphones',
    description: 'Up to 50 hours battery life with customized EQ and soft cushioned earcups. Great for focused study in crowded hostel corridors.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 1000,
    deposit: 1000,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 301,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Clean earpads with dry cloth before return', 'Do not sleep wearing headphones'],
    pickupMethod: 'Central Library silence zone foyer',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 21,
    createdAt: '2025-09-21T14:30:00Z',
  },
  {
    id: 'item-302',
    title: 'boAt Rockerz 450 On-Ear Bluetooth Headphones',
    category: 'headphones',
    description: 'Comfortable padded on-ear headset with punchy bass and 15-hour playback. Includes 3.5mm aux backup cable.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 600,
    deposit: 600,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 302,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Fold gently along hinges into pouch'],
    pickupMethod: 'Boys Hostel Block A lobby',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 4.7,
    borrowCount: 19,
    createdAt: '2025-09-22T09:15:00Z',
  },
  {
    id: 'item-303',
    title: 'JBL Go 3 Portable Bluetooth Speaker (IP67 Waterproof)',
    category: 'electronics',
    description: 'Ultra-portable rugged speaker with bold JBL Pro Sound. Ideal for campus acoustic practice, hostel birthday jams, or movie nights.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 700,
    deposit: 700,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 303,
    distance: 0.6,
    campus: 'Student Activity Centre',
    rules: ['Rinse with clean water if sand settles on grille', 'Keep volume within hostel hours limits'],
    pickupMethod: 'Student Activity Centre stage area',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 5.0,
    borrowCount: 25,
    createdAt: '2025-09-22T16:00:00Z',
  },
  {
    id: 'item-304',
    title: 'Realme Buds Wireless 2 Neo Neckband Earphones',
    category: 'headphones',
    description: 'Magnetic instant connection with environmental noise cancellation for voice calls and low-latency gaming mode.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 400,
    deposit: 400,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[8].id,
    owner: MOCK_USERS[8],
    imageSeed: 304,
    distance: 1.0,
    campus: 'Engineering Block',
    rules: ['Sanitize silicone ear tips before return', 'Charge with standard 5V charger'],
    pickupMethod: 'Engineering Block canteen',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 4.8,
    borrowCount: 12,
    createdAt: '2025-09-23T10:45:00Z',
  },
  {
    id: 'item-305',
    title: 'Wired Earphones with Inline Mic (Placement Interviews)',
    category: 'headphones',
    description: 'Zero audio latency 3.5mm earbuds with noise-isolating condenser microphone. Eliminates Bluetooth battery anxiety during hiring interviews.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 305,
    distance: 0.5,
    campus: 'Central Library',
    rules: ['Keep inside protective circular zip pouch'],
    pickupMethod: 'Central Library training lab',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 30,
    createdAt: '2025-09-23T12:00:00Z',
  },
  {
    id: 'item-306',
    title: '10-inch LED Ring Light with 6ft Extendable Tripod',
    category: 'cameras',
    description: '3 lighting modes (warm/white/natural) with 10 brightness levels and phone clamp mount. Perfect for online presentation defense or video resumes.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 500,
    deposit: 500,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[9].id,
    owner: MOCK_USERS[9],
    imageSeed: 306,
    distance: 0.7,
    campus: 'Student Activity Centre',
    rules: ['Tighten tripod wing nuts gently', 'Handle USB inline controller with care'],
    pickupMethod: 'SAC Media Room',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 18,
    createdAt: '2025-09-24T09:30:00Z',
  },
  {
    id: 'item-307',
    title: 'Digital Multimeter with Test Probes & Continuity Buzzer',
    category: 'tools',
    description: 'Measures AC/DC voltage, DC current, resistance, and transistor testing. Crucial for ECE/EEE circuit board debugging.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 350,
    deposit: 350,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 307,
    distance: 0.6,
    campus: 'Engineering Block',
    rules: ['Set selector knob back to OFF position after use', 'Do not probe unknown high mains voltages'],
    pickupMethod: 'Engineering Block Circuits Lab',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 22,
    createdAt: '2025-09-24T15:00:00Z',
  },
  {
    id: 'item-308',
    title: 'Soldering Iron Kit (60W, Temperature Controlled, Stand)',
    category: 'tools',
    description: 'Includes 60W adjustable iron (200°C–450°C), lead-free solder wire spool, desoldering pump, and safety metal stand.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 450,
    deposit: 450,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 308,
    distance: 0.8,
    campus: 'Engineering Block',
    rules: ['Work only in well-ventilated areas', 'Clean tip with damp sponge before shut-off'],
    pickupMethod: 'Hardware Maker Space, SAC',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.7,
    borrowCount: 14,
    createdAt: '2025-09-25T11:20:00Z',
  },
  {
    id: 'item-309',
    title: 'Canon EOS 1500D DSLR Camera (18-55mm IS II Lens)',
    category: 'cameras',
    description: '24.1MP APS-C CMOS sensor camera with optical viewfinder, Full HD video, and Wi-Fi transfer. Great for college cultural fests.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 6000,
    deposit: 6000,
    minTrustRequired: 75,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 309,
    distance: 0.4,
    campus: 'Central Library',
    rules: ['Requires Trust Score 75+', 'Always wear neck strap while shooting', 'Never touch camera sensor or front lens element'],
    pickupMethod: 'Central Library media lab',
    maxDurationDays: 2,
    suggestedDurationDays: 2,
    rating: 5.0,
    borrowCount: 11,
    createdAt: '2025-09-25T17:00:00Z',
  },
  {
    id: 'item-310',
    title: 'GoPro-Style 4K Action Camera with Waterproof Case',
    category: 'cameras',
    description: 'Wide-angle 170° action cam with bicycle handlebar mount, helmet clip, and 30m submersible housing for college sports day.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 3000,
    deposit: 3000,
    minTrustRequired: 70,
    available: false,
    availableFrom: '2026-10-03',
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 310,
    distance: 0.9,
    campus: 'Sports Complex',
    rules: ['Inspect waterproof rubber gasket seal before submerging', 'Rinse in fresh water after use'],
    pickupMethod: 'Sports Complex pavilion',
    maxDurationDays: 3,
    suggestedDurationDays: 2,
    rating: 4.8,
    borrowCount: 13,
    createdAt: '2025-09-26T08:30:00Z',
  },
  {
    id: 'item-311',
    title: 'Phone Tripod with Bluetooth Wireless Remote Shutter',
    category: 'cameras',
    description: 'Lightweight aluminum tripod reaching 130cm with 360-degree ball head and pocket Bluetooth clicker. Fits all iPhones and Androids.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 200,
    deposit: 200,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[9].id,
    owner: MOCK_USERS[9],
    imageSeed: 311,
    distance: 0.5,
    campus: 'Student Activity Centre',
    rules: ['Do not overtighten thumb screws'],
    pickupMethod: 'SAC Student Lounge',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 4.8,
    borrowCount: 28,
    createdAt: '2025-09-26T13:40:00Z',
  },

  // ── 4. Calculators and stationery ─────────────────────────────────────────
  {
    id: 'item-401',
    title: 'Casio FX-991EX ClassWiz Scientific Calculator',
    category: 'calculators',
    description: 'High-resolution natural textbook display with 552 functions including matrix, equation solver, integration, and spreadsheet mode.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 350,
    deposit: 350,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 401,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Keep in hard slide-on protective cover', 'Do not scribble on cover with permanent marker'],
    pickupMethod: 'Central Library reception desk',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 5.0,
    borrowCount: 42,
    createdAt: '2025-09-27T09:00:00Z',
  },
  {
    id: 'item-402',
    title: 'Casio FX-82MS Scientific Calculator (2-Line Display)',
    category: 'calculators',
    description: 'Simple and robust 240-function non-programmable scientific calculator. Permitted in university semester exams across all branches.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 402,
    distance: 0.5,
    campus: 'Science Block',
    rules: ['Do not scratch LCD display window', 'Return right after exam completion'],
    pickupMethod: 'Science Block lecture hall corridor',
    maxDurationDays: 7,
    suggestedDurationDays: 2,
    rating: 4.9,
    borrowCount: 38,
    createdAt: '2025-09-27T10:15:00Z',
  },
  {
    id: 'item-403',
    title: 'Texas Instruments TI-84 Plus CE Graphing Calculator',
    category: 'calculators',
    description: 'High-res backlit color screen graphing calculator with calculus, differential equations, and statistics tools preinstalled.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 1200,
    deposit: 1200,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 403,
    distance: 0.8,
    campus: 'Engineering Block',
    rules: ['Charge with supplied mini-USB cable', 'Do not clear RAM without owner consent'],
    pickupMethod: 'Engineering Block Mathematics dept foyer',
    maxDurationDays: 5,
    suggestedDurationDays: 3,
    rating: 4.9,
    borrowCount: 20,
    createdAt: '2025-09-27T12:00:00Z',
  },
  {
    id: 'item-404',
    title: 'Casio FX-991CW ClassWiz Scientific Calculator (Newest)',
    category: 'calculators',
    description: 'New intuitive design with 4-gradation display, cursor-based menu navigation, and math box simulations.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 400,
    deposit: 400,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 404,
    distance: 0.7,
    campus: 'Central Library',
    rules: ['Return with original sliding shell', 'Handle solar panel gently'],
    pickupMethod: 'Central Library main turnstile',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.9,
    borrowCount: 16,
    createdAt: '2025-09-27T14:40:00Z',
  },
  {
    id: 'item-405',
    title: 'Engineering Drawing Kit (Mini-Drafter, Set Squares, Clips)',
    category: 'stationery',
    description: 'Omega mini-drafter with stainless steel clamp, 45°/60° acrylic set squares, protractor, and sheet clips for 1st Year Engineering Drawing.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 400,
    deposit: 400,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[5].id,
    owner: MOCK_USERS[5],
    imageSeed: 405,
    distance: 0.6,
    campus: 'Engineering Block',
    rules: ['Loosen clamp bolt before adjusting drafting arm', 'Keep ruler edge free of ink stains'],
    pickupMethod: 'Engineering Drawing Hall 3',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 26,
    createdAt: '2025-09-27T16:00:00Z',
  },
  {
    id: 'item-406',
    title: 'Geometry Box & Precision Compass Set (Camlin/Maped)',
    category: 'stationery',
    description: 'Metal gear compass, divider, 15cm transparent ruler, and extra 0.5mm lead refill container in durable tin case.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 406,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Put protective cap back on sharp needle point'],
    pickupMethod: 'Girls Hostel visitor lobby',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 22,
    createdAt: '2025-09-28T09:30:00Z',
  },
  {
    id: 'item-407',
    title: 'Heavy Plastic Clipboard & Exam Pad (Transparent)',
    category: 'stationery',
    description: 'Smooth acrylic examination writing pad with strong stainless steel spring clip. Compliant with university exam hall rules.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 407,
    distance: 0.5,
    campus: 'Canteen Court',
    rules: ['Do not scratch formulas or ink marks on surface', 'Return same day after exam'],
    pickupMethod: 'Canteen Court entrance',
    maxDurationDays: 5,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 34,
    createdAt: '2025-09-28T11:00:00Z',
  },
  {
    id: 'item-408',
    title: 'A3 Wooden Drawing Board & Acrylic T-Square (60cm)',
    category: 'stationery',
    description: 'Seasoned pine-wood A3 drafting board with ebony working edge and clear beveled T-square for Architecture and Civil engineering students.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[5].id,
    owner: MOCK_USERS[5],
    imageSeed: 408,
    distance: 0.8,
    campus: 'Engineering Block',
    rules: ['Use drafting masking tape only; no push pins into wood surface'],
    pickupMethod: 'Architecture Studio 2 foyer',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 15,
    createdAt: '2025-09-28T14:15:00Z',
  },
  {
    id: 'item-409',
    title: 'Pastel Highlighter Set (6-Pack) & Fineliner Pens',
    category: 'stationery',
    description: 'Dual-tip aesthetic pastel highlighters and 0.4mm waterproof black fineliners for neat lab manual record submission.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[9].id,
    owner: MOCK_USERS[9],
    imageSeed: 409,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Always recap tightly after highlighting notes'],
    pickupMethod: 'Central Library ground floor cafe',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 29,
    createdAt: '2025-09-28T16:00:00Z',
  },

  // ── 5. Books (Indian syllabus mix) ─────────────────────────────────────────
  {
    id: 'item-501',
    title: 'Higher Engineering Mathematics (B.S. Grewal, 44th Edition)',
    category: 'books',
    description: 'The definitive engineering mathematics bible covering calculus, differential equations, Fourier series, and vector analysis. Clean pages.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 200,
    deposit: 200,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 501,
    distance: 0.2,
    campus: 'Central Library',
    rules: ['No ballpoint ink markings; light pencil underline only', 'Keep safe from water/tea spills'],
    pickupMethod: 'Central Library circulation desk',
    maxDurationDays: 21,
    suggestedDurationDays: 10,
    rating: 4.9,
    borrowCount: 36,
    createdAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'item-502',
    title: 'Data Structures Using C (Reema Thareja, 2nd Edition)',
    category: 'books',
    description: 'Lucid explanations of linked lists, trees, graphs, sorting, and recursion with complete C implementations and university exam questions.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 502,
    distance: 0.6,
    campus: 'Engineering Block',
    rules: ['Do not dog-ear pages; use a bookmark ribbon'],
    pickupMethod: 'CSE Department lobby',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 25,
    createdAt: '2025-09-21T11:00:00Z',
  },
  {
    id: 'item-503',
    title: 'Fundamentals of Physics (Halliday, Resnick & Walker)',
    category: 'books',
    description: 'Classic conceptual physics textbook for engineering mechanics, thermodynamics, and electromagnetism foundational courses.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 250,
    deposit: 250,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 503,
    distance: 0.5,
    campus: 'Science Block',
    rules: ['Handle spine gently — heavy hardcover edition'],
    pickupMethod: 'Science Block physics library',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 5.0,
    borrowCount: 18,
    createdAt: '2025-09-22T08:30:00Z',
  },
  {
    id: 'item-504',
    title: 'Organic Chemistry (Morrison and Boyd, 7th Edition)',
    category: 'books',
    description: 'Renowned chemistry text with thorough reaction mechanisms and synthesis pathways for B.Sc and pre-med practicals.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: false,
    availableFrom: '2026-10-04',
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 504,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Keep away from lab bench chemicals and open burners'],
    pickupMethod: 'Girls Hostel reception',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 21,
    createdAt: '2025-09-22T14:15:00Z',
  },
  {
    id: 'item-505',
    title: 'Principles of Economics (N. Gregory Mankiw, 8th Edition)',
    category: 'books',
    description: 'Clear introductory micro and macroeconomics text for B.Com, BBA, and minor elective humanities courses.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 250,
    deposit: 250,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 505,
    distance: 0.7,
    campus: 'Central Library',
    rules: ['Keep cover clean and dry'],
    pickupMethod: 'Central Library reading hall 2',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.7,
    borrowCount: 17,
    createdAt: '2025-09-23T16:00:00Z',
  },
  {
    id: 'item-506',
    title: 'Human Anatomy BD Chaurasia Vol 1 (Upper Limb & Thorax)',
    category: 'books',
    description: 'Standard medical dissection companion with clear multi-color anatomical diagrams for 1st Year MBBS students.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 350,
    deposit: 350,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 506,
    distance: 0.9,
    campus: 'Science Block',
    rules: ['Do not bring into wet dissection hall without plastic cover wrap'],
    pickupMethod: 'Science Block anatomy museum corridor',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.9,
    borrowCount: 24,
    createdAt: '2025-09-24T10:30:00Z',
  },
  {
    id: 'item-507',
    title: 'Concepts of Physics (H.C. Verma, Vol 1 & 2 Set)',
    category: 'books',
    description: 'The golden standard of problem-solving in physics. Includes solved short-answer questions and objective exercises.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 507,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Both volumes must be returned together'],
    pickupMethod: 'Central Library steps',
    maxDurationDays: 21,
    suggestedDurationDays: 14,
    rating: 5.0,
    borrowCount: 39,
    createdAt: '2025-09-24T15:30:00Z',
  },
  {
    id: 'item-508',
    title: 'Introduction to Algorithms (Cormen / CLRS 3rd Edition)',
    category: 'books',
    description: 'Comprehensive computer algorithms reference covering dynamic programming, greedy algorithms, and graph theory proofs.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 500,
    deposit: 500,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 508,
    distance: 0.7,
    campus: 'Engineering Block',
    rules: ['Heavy volume; protect spine when carrying in backpack'],
    pickupMethod: 'Engineering Block computer lab',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 5.0,
    borrowCount: 19,
    createdAt: '2025-09-25T11:00:00Z',
  },
  {
    id: 'item-509',
    title: 'Let Us C (Yashavant Kanetkar, 18th Edition)',
    category: 'books',
    description: 'Easy-to-understand beginner C programming textbook with step-by-step pointers, structures, and file management drills.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 509,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Return with CD/online code sheet intact inside back cover'],
    pickupMethod: 'Boys Hostel gate',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 31,
    createdAt: '2025-09-25T13:45:00Z',
  },
  {
    id: 'item-510',
    title: 'GATE Computer Science 2025 Chapterwise Solved Papers',
    category: 'books',
    description: '35 years of chapterwise questions with detailed explanations, test series mocks, and quick revision formula cheat sheets.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 510,
    distance: 0.2,
    campus: 'Central Library',
    rules: ['Do not mark answers directly in question blocks'],
    pickupMethod: 'Central Library reading porch',
    maxDurationDays: 21,
    suggestedDurationDays: 14,
    rating: 4.9,
    borrowCount: 28,
    createdAt: '2025-09-26T10:00:00Z',
  },

  // ── 6. Lab, hostel and daily life ─────────────────────────────────────────
  {
    id: 'item-601',
    title: 'White Unisex Lab Coat (Size Small, Pure Cotton)',
    category: 'lab-coats',
    description: 'Thick pure cotton lab coat with reinforced pockets and brass snaps. Freshly washed and starched for chemistry and biology practicals.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 601,
    distance: 0.3,
    campus: 'Science Block',
    rules: ['Wash and iron before returning', 'No bleach on college logo crest'],
    pickupMethod: 'Science Block chemistry foyer',
    maxDurationDays: 14,
    suggestedDurationDays: 4,
    rating: 4.9,
    borrowCount: 33,
    createdAt: '2025-09-20T08:00:00Z',
  },
  {
    id: 'item-602',
    title: 'White Unisex Lab Coat (Size Medium, Pure Cotton)',
    category: 'lab-coats',
    description: 'Full sleeves with knee-length cut. Clean and ironed, compliant with all college practical lab safety norms.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 602,
    distance: 0.4,
    campus: 'Science Block',
    rules: ['Wash before return if chemical spills occur'],
    pickupMethod: 'Science Block main notice board',
    maxDurationDays: 14,
    suggestedDurationDays: 4,
    rating: 4.8,
    borrowCount: 40,
    createdAt: '2025-09-20T09:30:00Z',
  },
  {
    id: 'item-603',
    title: 'White Unisex Lab Coat (Size Large, Pure Cotton)',
    category: 'lab-coats',
    description: 'Roomy fit with deep pen pockets and side pass-through slits for comfortable wear over winter sweaters or hoodies.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 603,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Wash before returning'],
    pickupMethod: 'Boys Hostel gate security',
    maxDurationDays: 14,
    suggestedDurationDays: 4,
    rating: 4.8,
    borrowCount: 27,
    createdAt: '2025-09-21T10:00:00Z',
  },
  {
    id: 'item-604',
    title: 'Lab Safety Goggles & Chemical Splash Shield',
    category: 'lab-coats',
    description: 'Anti-fog clear polycarbonate safety goggles with adjustable elastic strap. Fits easily over prescription glasses.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 604,
    distance: 0.4,
    campus: 'Science Block',
    rules: ['Clean lenses with soft microfibre cloth only; no harsh paper tissues'],
    pickupMethod: 'Science Block lab 2 entrance',
    maxDurationDays: 14,
    suggestedDurationDays: 3,
    rating: 4.9,
    borrowCount: 29,
    createdAt: '2025-09-21T15:20:00Z',
  },
  {
    id: 'item-605',
    title: 'Nitrile Lab Gloves Pack (Powder-Free, Box of 50)',
    category: 'lab-coats',
    description: 'Medical grade powder-free nitrile examination gloves for chemistry and biology hands-on lab experiments.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 605,
    distance: 0.6,
    campus: 'Science Block',
    rules: ['Take only required pairs and return remaining box neatly'],
    pickupMethod: 'Biochemistry department porch',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 16,
    createdAt: '2025-09-22T11:45:00Z',
  },
  {
    id: 'item-606',
    title: 'Medical Dissection Kit (14 Surgical Steel Instruments)',
    category: 'lab-coats',
    description: 'Includes fine scalpels with safety blades, dissecting scissors, forceps, seeker probe, and grooved director in a leatherette pouch.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 400,
    deposit: 400,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 606,
    distance: 0.5,
    campus: 'Science Block',
    rules: ['Sterilize in surgical spirit and dry completely before storing in pouch'],
    pickupMethod: 'Medical block lobby',
    maxDurationDays: 10,
    suggestedDurationDays: 5,
    rating: 5.0,
    borrowCount: 22,
    createdAt: '2025-09-23T09:10:00Z',
  },
  {
    id: 'item-607',
    title: 'Clinical Stethoscope (Littmann Classic Style, MBBS)',
    category: 'lab-coats',
    description: 'Dual-sided stainless steel chestpiece with tunable diaphragm and soft-sealing eartips for medical rounds and physiology practicals.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 1500,
    deposit: 1500,
    minTrustRequired: 70,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 607,
    distance: 0.5,
    campus: 'Science Block',
    rules: ['Wipe diaphragm and eartips with alcohol swab after use', 'Do not bend tubing tightly'],
    pickupMethod: 'Physiology department library',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 5.0,
    borrowCount: 14,
    createdAt: '2025-09-24T12:00:00Z',
  },
  {
    id: 'item-608',
    title: 'Electric Kettle 1.5L Stainless Steel (Pigeon/Prestige)',
    category: 'kitchen',
    description: 'Fast boiling 1500W automatic cut-off electric kettle. Indispensable for late night Maggi, black coffee, and green tea during exam week.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 608,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Never immerse kettle base in water', 'Rinse inside thoroughly before return'],
    pickupMethod: 'Boys Hostel Wing A foyer',
    maxDurationDays: 10,
    suggestedDurationDays: 5,
    rating: 4.9,
    borrowCount: 38,
    createdAt: '2025-09-24T16:40:00Z',
  },
  {
    id: 'item-609',
    title: 'Induction Cooktop 2000W (Hostel Approved)',
    category: 'kitchen',
    description: 'Push-button Indian menu options (Dosa, Chapati, Milk, Boil). Compatible with all flat-bottom induction steel vessels.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 800,
    deposit: 800,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 609,
    distance: 1.1,
    campus: 'Boys Hostel',
    rules: ['Wait for cooling fan to stop before unplugging cord', 'Wipe ceramic glass with moist cloth'],
    pickupMethod: 'Boys Hostel pantry',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 17,
    createdAt: '2025-09-25T10:00:00Z',
  },
  {
    id: 'item-610',
    title: 'Mini Mixer Grinder (3 Stainless Steel Jars, 500W)',
    category: 'kitchen',
    description: 'Compact 500W mixer grinder with chutney jar, dry grind jar, and wet blender. Perfect for fresh shakes or hostel cooking.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 500,
    deposit: 500,
    minTrustRequired: 0,
    available: false,
    availableFrom: '2026-10-02',
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 610,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Clean rubber gasket rings in jar lids thoroughly after use'],
    pickupMethod: 'Girls Hostel reception',
    maxDurationDays: 5,
    suggestedDurationDays: 2,
    rating: 4.8,
    borrowCount: 15,
    createdAt: '2025-09-25T14:30:00Z',
  },
  {
    id: 'item-611',
    title: 'Philips Heavy Dry Iron Box (1000W Non-Stick Soleplate)',
    category: 'hostel-essentials',
    description: 'Heavyweight classic dry iron with fabric temperature dial. Gives razor sharp creases to shirts and trousers for placement presentations.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 611,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Unplug immediately after use', 'Allow soleplate to cool before wrapping cord'],
    pickupMethod: 'Central Library side entrance',
    maxDurationDays: 4,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 45,
    createdAt: '2025-09-26T09:10:00Z',
  },
  {
    id: 'item-612',
    title: 'Hostel Heavy Plastic Bucket (20L) & Mug Set',
    category: 'hostel-essentials',
    description: 'Sturdy virgin plastic bathroom bucket and 1L graduated mug. Super useful for new semester arrivals and hostel check-ins.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 612,
    distance: 0.9,
    campus: 'Boys Hostel',
    rules: ['Rinse clean with water before return'],
    pickupMethod: 'Boys Hostel laundry area',
    maxDurationDays: 30,
    suggestedDurationDays: 14,
    rating: 4.7,
    borrowCount: 20,
    createdAt: '2025-09-26T12:00:00Z',
  },
  {
    id: 'item-613',
    title: 'Flexible Gooseneck Study Table Lamp (Warm White LED)',
    category: 'hostel-essentials',
    description: 'USB-rechargeable study lamp with touch dimmer and soft non-flicker eye protection light for room-mate friendly night studying.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 613,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Bend gooseneck smoothly without twisting'],
    pickupMethod: 'Girls Hostel lounge',
    maxDurationDays: 21,
    suggestedDurationDays: 7,
    rating: 4.9,
    borrowCount: 32,
    createdAt: '2025-09-26T15:30:00Z',
  },
  {
    id: 'item-614',
    title: 'High-Speed Aerodynamic Table Fan 400mm',
    category: 'hostel-essentials',
    description: 'Oscillating 3-speed copper motor desk fan with whisper-quiet airflow. Savior during humid hostel summer months.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 250,
    deposit: 250,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 614,
    distance: 1.0,
    campus: 'Boys Hostel',
    rules: ['Do not stick pens or items into blade guard'],
    pickupMethod: 'Boys Hostel reception',
    maxDurationDays: 14,
    suggestedDurationDays: 7,
    rating: 4.8,
    borrowCount: 23,
    createdAt: '2025-09-27T08:00:00Z',
  },
  {
    id: 'item-615',
    title: 'Rechargeable Mosquito Racket Bat (Built-in LED)',
    category: 'hostel-essentials',
    description: 'Powerful 3-layer safety mesh electric fly swatter with USB charging cable and bright searchlight.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 615,
    distance: 0.6,
    campus: 'Canteen Court',
    rules: ['Do not touch inner electrical grid mesh while power button is pressed'],
    pickupMethod: 'Canteen Court tea stall',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 29,
    createdAt: '2025-09-27T11:20:00Z',
  },
  {
    id: 'item-616',
    title: 'Windproof Compact Auto-Open Umbrella',
    category: 'umbrellas',
    description: 'Reinforced 9-rib fiberglass frame umbrella with one-touch open/close button. Built to withstand sudden monsoon downpours.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 616,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Let canopy air dry before collapsing into sleeve cover'],
    pickupMethod: 'Central Library entrance',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 37,
    createdAt: '2025-09-27T14:00:00Z',
  },
  {
    id: 'item-617',
    title: 'Waterproof Full Raincoat with Drawstring Hood & Pouch',
    category: 'umbrellas',
    description: 'Heavy duty waterproof PVC raincoat with sealed seams, reflector strip back, and matching travel pouch.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[8].id,
    owner: MOCK_USERS[8],
    imageSeed: 617,
    distance: 0.7,
    campus: 'Engineering Block',
    rules: ['Hang dry in shade before returning'],
    pickupMethod: 'Engineering Block porch',
    maxDurationDays: 5,
    suggestedDurationDays: 2,
    rating: 4.7,
    borrowCount: 18,
    createdAt: '2025-09-27T16:30:00Z',
  },
  {
    id: 'item-618',
    title: "Men's Navy Formal Blazer (Size 38R, Placement Ready)",
    category: 'hostel-essentials',
    description: 'Slim fit tailored 2-button navy blazer. Dry cleaned and ready for campus placement interviews and conference presentations.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 618,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Hang on wooden coat hanger when not wearing; no food stains'],
    pickupMethod: 'Central Library placement cell wing',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 22,
    createdAt: '2025-09-28T09:00:00Z',
  },
  {
    id: 'item-619',
    title: "Women's Black Formal Blazer (Size 36, Placement Ready)",
    category: 'hostel-essentials',
    description: 'Single-breasted elegant formal blazer with satin lining. Ideal for corporate interviews, moot court, and conference chairing.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 619,
    distance: 0.4,
    campus: 'Girls Hostel',
    rules: ['Return inside protective garment zip cover'],
    pickupMethod: 'Girls Hostel front gate',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 5.0,
    borrowCount: 19,
    createdAt: '2025-09-28T11:30:00Z',
  },
  {
    id: 'item-620',
    title: 'Traditional Silk Kurta Pajama Set (Festive/Cultural)',
    category: 'hostel-essentials',
    description: 'Maroon raw silk kurta with gold embroidery and matching churidar for Diwali campus night, ethnic day, or college fest inaugurations.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 350,
    deposit: 350,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 620,
    distance: 0.8,
    campus: 'Student Activity Centre',
    rules: ['Dry clean or delicate hand wash only before return'],
    pickupMethod: 'Student Activity Centre cultural room',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 16,
    createdAt: '2025-09-28T15:00:00Z',
  },

  // ── 7. Sports ─────────────────────────────────────────────────────────────
  {
    id: 'item-701',
    title: 'Kashmir Willow Cricket Bat + Leather Ball & Batting Pads',
    category: 'sports',
    description: 'Short handle seasoned Kashmir willow bat with thick edges, sweet spot knocked in. Includes leather ball and light batting leg pads.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 300,
    deposit: 300,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 701,
    distance: 0.6,
    campus: 'Sports Complex',
    rules: ['Do not use against wet tennis balls or puddle ground', 'Wipe bat face clean after play'],
    pickupMethod: 'Sports Complex cricket nets',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 31,
    createdAt: '2025-09-22T15:00:00Z',
  },
  {
    id: 'item-702',
    title: 'Yonex Badminton Racket Set (2 Rackets + Shuttlecock Tube)',
    category: 'sports',
    description: 'Isometric aluminum frame rackets with tight 24-lb string tension and tube of 3 Mavis 350 nylon shuttlecocks in zippered cover.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[1].id,
    owner: MOCK_USERS[1],
    imageSeed: 702,
    distance: 0.4,
    campus: 'Sports Complex',
    rules: ['Avoid clashing racket heads during doubles play'],
    pickupMethod: 'Indoor Badminton Court foyer',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 44,
    createdAt: '2025-09-23T16:15:00Z',
  },
  {
    id: 'item-703',
    title: 'Nivia Storm Football (Size 5, All-Weather Rubber)',
    category: 'sports',
    description: '32-panel FIFA standard football with hand pump and air pressure needle. Great grip on turf and grass.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[8].id,
    owner: MOCK_USERS[8],
    imageSeed: 703,
    distance: 0.5,
    campus: 'Sports Complex',
    rules: ['Wipe clean of mud after game; return with pump needle in sheath'],
    pickupMethod: 'Sports Complex main football ground pavilion',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 26,
    createdAt: '2025-09-24T17:00:00Z',
  },
  {
    id: 'item-704',
    title: 'Spalding Basketball (Size 7, Composite Leather)',
    category: 'sports',
    description: 'Official match ball with deep channel design for superior grip and true bounce on both indoor hardwood and outdoor courts.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[6].id,
    owner: MOCK_USERS[6],
    imageSeed: 704,
    distance: 0.5,
    campus: 'Sports Complex',
    rules: ['Do not kick like a football; return with pump'],
    pickupMethod: 'Outdoor Basketball Court gate',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 28,
    createdAt: '2025-09-25T17:30:00Z',
  },
  {
    id: 'item-705',
    title: 'Anti-Skid Yoga Mat 6mm with Carry Strap',
    category: 'sports',
    description: 'High-density eco-friendly TPE foam yoga mat with textured grip. Perfect for morning yoga, stretching, or hostel room fitness.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[3].id,
    owner: MOCK_USERS[3],
    imageSeed: 705,
    distance: 0.4,
    campus: 'Science Block',
    rules: ['Wipe down with sanitizer cloth after workout'],
    pickupMethod: 'Science Block gym room',
    maxDurationDays: 7,
    suggestedDurationDays: 3,
    rating: 4.8,
    borrowCount: 21,
    createdAt: '2025-09-26T07:30:00Z',
  },
  {
    id: 'item-706',
    title: 'Synco Carrom Board 32" with Coins, Striker & Powder',
    category: 'sports',
    description: 'Tournament grade 32-inch carrom board with English birch ply, heavy acrylic tournament striker, and boric powder bottle.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 400,
    deposit: 400,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 706,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Do not place cold glasses of water on board surface', 'Count all 19 carrom men before returning'],
    pickupMethod: 'Boys Hostel recreation room',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 5.0,
    borrowCount: 35,
    createdAt: '2025-09-26T18:00:00Z',
  },
  {
    id: 'item-707',
    title: 'Tournament Wooden Chess Board & Weighted Pieces',
    category: 'sports',
    description: 'Folding solid sheesham wood chess board (14x14 inch) with hand-carved Staunton weighted pieces and felted bottoms.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 707,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Check all 32 pieces into the velvet slots inside board'],
    pickupMethod: 'Central Library chess club alcove',
    maxDurationDays: 4,
    suggestedDurationDays: 2,
    rating: 5.0,
    borrowCount: 27,
    createdAt: '2025-09-27T12:30:00Z',
  },
  {
    id: 'item-708',
    title: 'Table Tennis Racket Pair + 3 Stiga Competition Balls',
    category: 'sports',
    description: 'ITTF approved rubber TT bats with 5-ply wood blade and flared ergonomic handle for spin and control.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[7].id,
    owner: MOCK_USERS[7],
    imageSeed: 708,
    distance: 0.6,
    campus: 'Student Activity Centre',
    rules: ['Avoid peeling rubber edges', 'Return balls in plastic case'],
    pickupMethod: 'SAC Table Tennis Arena',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.8,
    borrowCount: 32,
    createdAt: '2025-09-27T16:00:00Z',
  },

  // ── 8. Tools ──────────────────────────────────────────────────────────────
  {
    id: 'item-801',
    title: 'Basic Hostel DIY Tool Kit (Hammer, Plier, Screwdrivers, Tape)',
    category: 'tools',
    description: 'Includes claw hammer, combination pliers, 6 reversible screwdrivers, 5m measuring tape, and electrical insulation tape in hard toolbox.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[2].id,
    owner: MOCK_USERS[2],
    imageSeed: 801,
    distance: 0.8,
    campus: 'Boys Hostel',
    rules: ['Wipe all metal tool heads before packing into toolbox'],
    pickupMethod: 'Boys Hostel maintenance desk',
    maxDurationDays: 3,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 30,
    createdAt: '2025-09-28T10:00:00Z',
  },
  {
    id: 'item-802',
    title: 'Bosch 18V Cordless Electric Drill Set with Masonry Bits',
    category: 'tools',
    description: 'Bosch Professional drill/driver with 2x 2.0Ah lithium batteries, quick charger, and 32-piece masonry & wood bit set. Great for wall mounting.',
    condition: 'Good',
    dailyRate: 0,
    depositINR: 600,
    deposit: 600,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[4].id,
    owner: MOCK_USERS[4],
    imageSeed: 802,
    distance: 0.7,
    campus: 'Engineering Block',
    rules: ['Wear eye safety goggles when drilling', 'Recharge battery fully before returning'],
    pickupMethod: 'Engineering Block Workshop',
    maxDurationDays: 2,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 16,
    createdAt: '2025-09-28T13:30:00Z',
  },
  {
    id: 'item-803',
    title: 'Precision Screwdriver Set 32-in-1 (Phone/Laptop Repair)',
    category: 'tools',
    description: 'Torx, Phillips, Pentalobe, and flat precision bits with magnetic extension shaft. Perfect for upgrading laptop RAM or cleaning fan dust.',
    condition: 'Excellent',
    dailyRate: 0,
    depositINR: 0,
    deposit: 0,
    minTrustRequired: 0,
    available: true,
    ownerId: MOCK_USERS[0].id,
    owner: MOCK_USERS[0],
    imageSeed: 803,
    distance: 0.3,
    campus: 'Central Library',
    rules: ['Press bits firmly into magnet holder so none fall out'],
    pickupMethod: 'Central Library reading hall',
    maxDurationDays: 4,
    suggestedDurationDays: 1,
    rating: 4.9,
    borrowCount: 27,
    createdAt: '2025-09-28T15:15:00Z',
  },
];

export const MOCK_BORROW_REQUESTS: BorrowRequest[] = [
  {
    id: '30000000-0000-0000-0000-000000000001',
    itemId: 'item-401',
    item: MOCK_ITEMS[33], // Casio ClassWiz
    borrowerId: MOCK_USERS[0].id,
    borrower: MOCK_USERS[0],
    lenderId: MOCK_USERS[1].id,
    lender: MOCK_USERS[1],
    startDate: '2025-10-05',
    endDate: '2025-10-07',
    message: 'Hey Ananya, have my semester mathematics exam this Tuesday. Would love to borrow your ClassWiz calculator!',
    status: 'accepted',
    createdAt: '2025-09-24T10:00:00Z',
  },
  {
    id: '30000000-0000-0000-0000-000000000002',
    itemId: 'item-602',
    item: MOCK_ITEMS[43], // Lab coat Size M
    borrowerId: MOCK_USERS[4].id,
    borrower: MOCK_USERS[4],
    lenderId: MOCK_USERS[3].id,
    lender: MOCK_USERS[3],
    startDate: '2025-10-06',
    endDate: '2025-10-08',
    message: 'Hi Priya, needed a clean lab coat for our chemistry practical viva this Thursday.',
    status: 'pending',
    createdAt: '2025-09-27T14:00:00Z',
  },
  {
    id: '30000000-0000-0000-0000-000000000003',
    itemId: 'item-702',
    item: MOCK_ITEMS[53], // Yonex badminton set
    borrowerId: MOCK_USERS[2].id,
    borrower: MOCK_USERS[2],
    lenderId: MOCK_USERS[1].id,
    lender: MOCK_USERS[1],
    startDate: '2025-09-20',
    endDate: '2025-09-21',
    message: 'Planning an evening badminton match at the Sports Complex with wingmates!',
    status: 'returned',
    createdAt: '2025-09-19T09:00:00Z',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '20000000-0000-0000-0000-000000000001',
    type: 'lend',
    text: 'Aarav just lent a Casio ClassWiz calculator',
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000002',
    type: 'return',
    text: 'Priya returned a Lab Coat on time (100% score)',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000003',
    type: 'save',
    text: 'Rohan saved ₹2,500 borrowing textbooks this semester',
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000004',
    type: 'list',
    text: 'Sneha listed a Drafter & Drawing Board kit',
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000005',
    type: 'lend',
    text: 'Karthik lent a Kashmir Willow Cricket Kit',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
];

export const CATEGORY_META: Record<Category, { label: string; icon: string; color: string; gradient: string }> = {
  calculators: { label: 'Calculators', icon: '🧮', color: 'indigo', gradient: 'from-indigo-50 to-indigo-100' },
  'lab-coats': { label: 'Lab Coats', icon: '🥼', color: 'teal', gradient: 'from-teal-50 to-teal-100' },
  books: { label: 'Books & Notes', icon: '📚', color: 'amber', gradient: 'from-amber-50 to-amber-100' },
  chargers: { label: 'Chargers', icon: '🔌', color: 'purple', gradient: 'from-purple-50 to-purple-100' },
  adapters: { label: 'Adapters', icon: '🔄', color: 'blue', gradient: 'from-blue-50 to-blue-100' },
  'power-banks': { label: 'Power Banks', icon: '🔋', color: 'emerald', gradient: 'from-emerald-50 to-emerald-100' },
  laptops: { label: 'Laptops', icon: '💻', color: 'sky', gradient: 'from-sky-50 to-sky-100' },
  headphones: { label: 'Headphones', icon: '🎧', color: 'rose', gradient: 'from-rose-50 to-rose-100' },
  electronics: { label: 'Electronics', icon: '⚡', color: 'cyan', gradient: 'from-cyan-50 to-cyan-100' },
  umbrellas: { label: 'Umbrellas', icon: '☂️', color: 'violet', gradient: 'from-violet-50 to-violet-100' },
  sports: { label: 'Sports Gear', icon: '🏏', color: 'green', gradient: 'from-green-50 to-green-100' },
  tools: { label: 'Tools', icon: '🔧', color: 'orange', gradient: 'from-orange-50 to-orange-100' },
  kitchen: { label: 'Kitchen', icon: '🍳', color: 'red', gradient: 'from-red-50 to-red-100' },
  stationery: { label: 'Stationery', icon: '📐', color: 'yellow', gradient: 'from-yellow-50 to-yellow-100' },
  'hostel-essentials': { label: 'Hostel Essentials', icon: '🏠', color: 'stone', gradient: 'from-stone-50 to-stone-100' },
  cameras: { label: 'Cameras', icon: '📷', color: 'pink', gradient: 'from-pink-50 to-pink-100' },
};

export const ALL_CATEGORIES: Category[] = [
  'calculators',
  'lab-coats',
  'books',
  'chargers',
  'adapters',
  'power-banks',
  'laptops',
  'headphones',
  'electronics',
  'umbrellas',
  'sports',
  'tools',
  'kitchen',
  'stationery',
  'hostel-essentials',
  'cameras',
];

export const STATS = {
  totalBorrows: 8420,
  activeLenders: 2150,
  itemsListed: 5800,
  totalSavedINR: '15,00,000+',
  avgSavings: 4500,
};
